[1mdiff --git "a/`\357\200\211\357\200\211" "b/`\357\200\211\357\200\211"[m
[1mdeleted file mode 100644[m
[1mindex c1e8210..0000000[m
[1m--- "a/`\357\200\211\357\200\211"[m
[1m+++ /dev/null[m
[36m@@ -1,146 +0,0 @@[m
[31m-[1mdiff --git a/src/main/webapp/asset/img/mecbrand.mp4 b/src/main/webapp/asset/img/mecbrand.mp4[m[m
[31m-[1mindex 8043a6b..7bd1728 100644[m[m
[31m-Binary files a/src/main/webapp/asset/img/mecbrand.mp4 and b/src/main/webapp/asset/img/mecbrand.mp4 differ[m
[31m-[1mdiff --git a/target/DriveXO_Management_Project-1.0-SNAPSHOT/WEB-INF/classes/DB/DBContext.class b/target/DriveXO_Management_Project-1.0-SNAPSHOT/WEB-INF/classes/DB/DBContext.class[m[m
[31m-[1mindex 133322a..50d0cd1 100644[m[m
[31m-Binary files a/target/DriveXO_Management_Project-1.0-SNAPSHOT/WEB-INF/classes/DB/DBContext.class and b/target/DriveXO_Management_Project-1.0-SNAPSHOT/WEB-INF/classes/DB/DBContext.class differ[m
[31m-[1mdiff --git a/target/DriveXO_Management_Project-1.0-SNAPSHOT/asset/img/mecbrand.mp4 b/target/DriveXO_Management_Project-1.0-SNAPSHOT/asset/img/mecbrand.mp4[m[m
[31m-[1mindex 8043a6b..7bd1728 100644[m[m
[31m-Binary files a/target/DriveXO_Management_Project-1.0-SNAPSHOT/asset/img/mecbrand.mp4 and b/target/DriveXO_Management_Project-1.0-SNAPSHOT/asset/img/mecbrand.mp4 differ[m
[31m-[1mdiff --git a/target/classes/DB/DBContext.class b/target/classes/DB/DBContext.class[m[m
[31m-[1mindex 133322a..50d0cd1 100644[m[m
[31m-Binary files a/target/classes/DB/DBContext.class and b/target/classes/DB/DBContext.class differ[m
[31m-[1mdiff --git a/target/maven-status/maven-compiler-plugin/compile/default-compile/createdFiles.lst b/target/maven-status/maven-compiler-plugin/compile/default-compile/createdFiles.lst[m[m
[31m-[1mindex bd271c4..3074d18 100644[m[m
[31m-[1m--- a/target/maven-status/maven-compiler-plugin/compile/default-compile/createdFiles.lst[m[m
[31m-[1m+++ b/target/maven-status/maven-compiler-plugin/compile/default-compile/createdFiles.lst[m[m
[31m-[36m@@ -1,38 +1,38 @@[m[m
[31m-[31m-DAO/CartDAO.class[m[m
[31m-[31m-Controller/AddToCartServlet.class[m[m
[31m-[31m-Controller/CarImageServlet.class[m[m
[31m-[31m-Controller/HomeServlet.class[m[m
[31m-[31m-Model/Role.class[m[m
[31m-[31m-DAO/CarDAO.class[m[m
[31m-[31m-Model/User.class[m[m
[31m-[31m-DAO/OrderDAO.class[m[m
[31m-[31m-Controller/AdminDashboardServlet.class[m[m
[31m-[31m-DB/DBContext.class[m[m
[31m-[31m-Controller/AdminCarServlet.class[m[m
[31m-[31m-DAO/CarAppointmentDAO.class[m[m
[31m-[31m-Model/Category.class[m[m
[31m-[31m-Controller/CarDetailServlet.class[m[m
[31m-[31m-Controller/StaffPartServlet.class[m[m
[31m-[31m-com/mycompany/drivexo_management_project/JakartaRestConfiguration.class[m[m
[31m-[31m-Controller/CartServlet.class[m[m
[31m-[31m-Model/Cart.class[m[m
[31m-[31m-Controller/CarListServlet.class[m[m
[31m-[31m-DB/TestDBConnect.class[m[m
[31m-[31m-com/mycompany/drivexo_management_project/resources/JakartaEE10Resource.class[m[m
[31m-[31m-Model/Order.class[m[m
[31m-[31m-Model/Part.class[m[m
[31m-[31m-DAO/UserDAO.class[m[m
[31m-[31m-Model/Service.class[m[m
[31m-[31m-DAO/ServiceDAO.class[m[m
[31m-[31m-DAO/ServiceScheduleDAO.class[m[m
[31m-[31m-DAO/OrderDetailDAO.class[m[m
[31m-[31m-Model/Comment.class[m[m
[31m-[31m-DAO/RoleDAO.class[m[m
[31m-[31m-Model/ServiceSchedule.class[m[m
[31m-[31m-Model/Payment.class[m[m
[31m-[31m-Controller/AdminPartServlet.class[m[m
[31m-[31m-Controller/BookingsServlet.class[m[m
[31m-[31m-Controller/PartServlet.class[m[m
[31m-[31m-DAO/PartDAO.class[m[m
[31m-[31m-Model/CarAppointment.class[m[m
[31m-[31m-Model/Car.class[m[m
[31m-[32m+[m[32mDAO\CartDAO.class[m[m
[31m-[32m+[m[32mModel\CarAppointment.class[m[m
[31m-[32m+[m[32mDAO\CarAppointmentDAO.class[m[m
[31m-[32m+[m[32mModel\Part.class[m[m
[31m-[32m+[m[32mModel\Category.class[m[m
[31m-[32m+[m[32mController\AdminDashboardServlet.class[m[m
[31m-[32m+[m[32mController\CarImageServlet.class[m[m
[31m-[32m+[m[32mDAO\CarDAO.class[m[m
[31m-[32m+[m[32mDAO\ServiceDAO.class[m[m
[31m-[32m+[m[32mController\BookingsServlet.class[m[m
[31m-[32m+[m[32mModel\Car.class[m[m
[31m-[32m+[m[32mModel\Cart.class[m[m
[31m-[32m+[m[32mDAO\PartDAO.class[m[m
[31m-[32m+[m[32mDAO\ServiceScheduleDAO.class[m[m
[31m-[32m+[m[32mModel\Comment.class[m[m
[31m-[32m+[m[32mDAO\RoleDAO.class[m[m
[31m-[32m+[m[32mController\CarListServlet.class[m[m
[31m-[32m+[m[32mcom\mycompany\drivexo_management_project\JakartaRestConfiguration.class[m[m
[31m-[32m+[m[32mController\AddToCartServlet.class[m[m
[31m-[32m+[m[32mDAO\OrderDetailDAO.class[m[m
[31m-[32m+[m[32mController\AdminCarServlet.class[m[m
[31m-[32m+[m[32mModel\Service.class[m[m
[31m-[32m+[m[32mController\CartServlet.class[m[m
[31m-[32m+[m[32mModel\Order.class[m[m
[31m-[32m+[m[32mController\StaffPartServlet.class[m[m
[31m-[32m+[m[32mModel\Payment.class[m[m
[31m-[32m+[m[32mDAO\UserDAO.class[m[m
[31m-[32m+[m[32mDAO\OrderDAO.class[m[m
[31m-[32m+[m[32mDB\TestDBConnect.class[m[m
[31m-[32m+[m[32mcom\mycompany\drivexo_management_project\resources\JakartaEE10Resource.class[m[m
[31m-[32m+[m[32mController\CarDetailServlet.class[m[m
[31m-[32m+[m[32mController\AdminPartServlet.class[m[m
[31m-[32m+[m[32mModel\ServiceSchedule.class[m[m
[31m-[32m+[m[32mDB\DBContext.class[m[m
[31m-[32m+[m[32mModel\User.class[m[m
[31m-[32m+[m[32mController\PartServlet.class[m[m
[31m-[32m+[m[32mModel\Role.class[m[m
[31m-[32m+[m[32mController\HomeServlet.class[m[m
[31m-[1mdiff --git a/target/maven-status/maven-compiler-plugin/compile/default-compile/inputFiles.lst b/target/maven-status/maven-compiler-plugin/compile/default-compile/inputFiles.lst[m[m
[31m-[1mindex 095048f..a03625a 100644[m[m
[31m-[1m--- a/target/maven-status/maven-compiler-plugin/compile/default-compile/inputFiles.lst[m[m
[31m-[1m+++ b/target/maven-status/maven-compiler-plugin/compile/default-compile/inputFiles.lst[m[m
[31m-[36m@@ -1,4 +1,3 @@[m[m
[31m-[31m-<<<<<<< HEAD[m[m
[31m- C:\Users\acer\Desktop\SWP_Management\DriveXO_Management_Project\src\main\java\DAO\OrderDetailDAO.java[m[m
[31m- C:\Users\acer\Desktop\SWP_Management\DriveXO_Management_Project\src\main\java\Model\Payment.java[m[m
[31m- C:\Users\acer\Desktop\SWP_Management\DriveXO_Management_Project\src\main\java\Model\Comment.java[m[m
[31m-[36m@@ -37,43 +36,3 @@[m [mC:\Users\acer\Desktop\SWP_Management\DriveXO_Management_Project\src\main\java\DA[m[m
[31m- C:\Users\acer\Desktop\SWP_Management\DriveXO_Management_Project\src\main\java\DAO\CartDAO.java[m[m
[31m- C:\Users\acer\Desktop\SWP_Management\DriveXO_Management_Project\src\main\java\DB\TestDBConnect.java[m[m
[31m- C:\Users\acer\Desktop\SWP_Management\DriveXO_Management_Project\src\main\java\Model\Service.java[m[m
[31m-[31m-=======[m[m
[31m-[31m-/Users/giahuy/Desktop/SWP_PROJECT/src/main/java/DAO/CartDAO.java[m[m
[31m-[31m-/Users/giahuy/Desktop/SWP_PROJECT/src/main/java/Model/User.java[m[m
[31m-[31m-/Users/giahuy/Desktop/SWP_PROJECT/src/main/java/Controller/AdminPartServlet.java[m[m
[31m-[31m-/Users/giahuy/Desktop/SWP_PROJECT/src/main/java/DAO/CarAppointmentDAO.java[m[m
[31m-[31m-/Users/giahuy/Desktop/SWP_PROJECT/src/main/java/Controller/AddToCartServlet.java[m[m
[31m-[31m-/Users/giahuy/Desktop/SWP_PROJECT/src/main/java/Model/Order.java[m[m
[31m-[31m-/Users/giahuy/Desktop/SWP_PROJECT/src/main/java/Model/ServiceSchedule.java[m[m
[31m-[31m-/Users/giahuy/Desktop/SWP_PROJECT/src/main/java/Controller/CarDetailServlet.java[m[m
[31m-[31m-/Users/giahuy/Desktop/SWP_PROJECT/src/main/java/Model/Service.java[m[m
[31m-[31m-/Users/giahuy/Desktop/SWP_PROJECT/src/main/java/DAO/ServiceDAO.java[m[m
[31m-[31m-/Users/giahuy/Desktop/SWP_PROJECT/src/main/java/DAO/PartDAO.java[m[m
[31m-[31m-/Users/giahuy/Desktop/SWP_PROJECT/src/main/java/Model/Role.java[m[m
[31m-[31m-/Users/giahuy/Desktop/SWP_PROJECT/src/main/java/DB/TestDBConnect.java[m[m
[31m-[31m-/Users/giahuy/Desktop/SWP_PROJECT/src/main/java/DAO/CarDAO.java[m[m
[31m-[31m-/Users/giahuy/Desktop/SWP_PROJECT/src/main/java/com/mycompany/drivexo_management_project/resources/JakartaEE10Resource.java[m[m
[31m-[31m-/Users/giahuy/Desktop/SWP_PROJECT/src/main/java/Model/Payment.java[m[m
[31m-[31m-/Users/giahuy/Desktop/SWP_PROJECT/src/main/java/Controller/BookingsServlet.java[m[m
[31m-[31m-/Users/giahuy/Desktop/SWP_PROJECT/src/main/java/Controller/CarListServlet.java[m[m
[31m-[31m-/Users/giahuy/Desktop/SWP_PROJECT/src/main/java/DAO/UserDAO.java[m[m
[31m-[31m-/Users/giahuy/Desktop/SWP_PROJECT/src/main/java/Controller/AdminDashboardServlet.java[m[m
[31m-[31m-/Users/giahuy/Desktop/SWP_PROJECT/src/main/java/Model/Category.java[m[m
[31m-[31m-/Users/giahuy/Desktop/SWP_PROJECT/src/main/java/Controller/HomeServlet.java[m[m
[31m-[31m-/Users/giahuy/Desktop/SWP_PROJECT/src/main/java/Model/Cart.java[m[m
[31m-[31m-/Users/giahuy/Desktop/SWP_PROJECT/src/main/java/DB/DBContext.java[m[m
[31m-[31m-/Users/giahuy/Desktop/SWP_PROJECT/src/main/java/DAO/OrderDAO.java[m[m
[31m-[31m-/Users/giahuy/Desktop/SWP_PROJECT/src/main/java/Model/Part.java[m[m
[31m-[31m-/Users/giahuy/Desktop/SWP_PROJECT/src/main/java/Model/Comment.java[m[m
[31m-[31m-/Users/giahuy/Desktop/SWP_PROJECT/src/main/java/DAO/RoleDAO.java[m[m
[31m-[31m-/Users/giahuy/Desktop/SWP_PROJECT/src/main/java/Controller/PartServlet.java[m[m
[31m-[31m-/Users/giahuy/Desktop/SWP_PROJECT/src/main/java/DAO/OrderDetailDAO.java[m[m
[31m-[31m-/Users/giahuy/Desktop/SWP_PROJECT/src/main/java/Model/Car.java[m[m
[31m-[31m-/Users/giahuy/Desktop/SWP_PROJECT/src/main/java/com/mycompany/drivexo_management_project/JakartaRestConfiguration.java[m[m
[31m-[31m-/Users/giahuy/Desktop/SWP_PROJECT/src/main/java/Controller/StaffPartServlet.java[m[m
[31m-[31m-/Users/giahuy/Desktop/SWP_PROJECT/src/main/java/Controller/CartServlet.java[m[m
[31m-[31m-/Users/giahuy/Desktop/SWP_PROJECT/src/main/java/Controller/AdminCarServlet.java[m[m
[31m-[31m-/Users/giahuy/Desktop/SWP_PROJECT/src/main/java/Controller/CarImageServlet.java[m[m
[31m-[31m-/Users/giahuy/Desktop/SWP_PROJECT/src/main/java/Model/CarAppointment.java[m[m
[31m-[31m-/Users/giahuy/Desktop/SWP_PROJECT/src/main/java/DAO/ServiceScheduleDAO.java[m[m
[31m-[31m->>>>>>> d73b885b167a0650e6479c2b7a42f09c07d71828[m[m
[1mdiff --git a/clear b/clear[m
[1mdeleted file mode 100644[m
[1mindex c1e8210..0000000[m
[1m--- a/clear[m
[1m+++ /dev/null[m
[36m@@ -1,146 +0,0 @@[m
[31m-[1mdiff --git a/src/main/webapp/asset/img/mecbrand.mp4 b/src/main/webapp/asset/img/mecbrand.mp4[m[m
[31m-[1mindex 8043a6b..7bd1728 100644[m[m
[31m-Binary files a/src/main/webapp/asset/img/mecbrand.mp4 and b/src/main/webapp/asset/img/mecbrand.mp4 differ[m
[31m-[1mdiff --git a/target/DriveXO_Management_Project-1.0-SNAPSHOT/WEB-INF/classes/DB/DBContext.class b/target/DriveXO_Management_Project-1.0-SNAPSHOT/WEB-INF/classes/DB/DBContext.class[m[m
[31m-[1mindex 133322a..50d0cd1 100644[m[m
[31m-Binary files a/target/DriveXO_Management_Project-1.0-SNAPSHOT/WEB-INF/classes/DB/DBContext.class and b/target/DriveXO_Management_Project-1.0-SNAPSHOT/WEB-INF/classes/DB/DBContext.class differ[m
[31m-[1mdiff --git a/target/DriveXO_Management_Project-1.0-SNAPSHOT/asset/img/mecbrand.mp4 b/target/DriveXO_Management_Project-1.0-SNAPSHOT/asset/img/mecbrand.mp4[m[m
[31m-[1mindex 8043a6b..7bd1728 100644[m[m
[31m-Binary files a/target/DriveXO_Management_Project-1.0-SNAPSHOT/asset/img/mecbrand.mp4 and b/target/DriveXO_Management_Project-1.0-SNAPSHOT/asset/img/mecbrand.mp4 differ[m
[31m-[1mdiff --git a/target/classes/DB/DBContext.class b/target/classes/DB/DBContext.class[m[m
[31m-[1mindex 133322a..50d0cd1 100644[m[m
[31m-Binary files a/target/classes/DB/DBContext.class and b/target/classes/DB/DBContext.class differ[m
[31m-[1mdiff --git a/target/maven-status/maven-compiler-plugin/compile/default-compile/createdFiles.lst b/target/maven-status/maven-compiler-plugin/compile/default-compile/createdFiles.lst[m[m
[31m-[1mindex bd271c4..3074d18 100644[m[m
[31m-[1m--- a/target/maven-status/maven-compiler-plugin/compile/default-compile/createdFiles.lst[m[m
[31m-[1m+++ b/target/maven-status/maven-compiler-plugin/compile/default-compile/createdFiles.lst[m[m
[31m-[36m@@ -1,38 +1,38 @@[m[m
[31m-[31m-DAO/CartDAO.class[m[m
[31m-[31m-Controller/AddToCartServlet.class[m[m
[31m-[31m-Controller/CarImageServlet.class[m[m
[31m-[31m-Controller/HomeServlet.class[m[m
[31m-[31m-Model/Role.class[m[m
[31m-[31m-DAO/CarDAO.class[m[m
[31m-[31m-Model/User.class[m[m
[31m-[31m-DAO/OrderDAO.class[m[m
[31m-[31m-Controller/AdminDashboardServlet.class[m[m
[31m-[31m-DB/DBContext.class[m[m
[31m-[31m-Controller/AdminCarServlet.class[m[m
[31m-[31m-DAO/CarAppointmentDAO.class[m[m
[31m-[31m-Model/Category.class[m[m
[31m-[31m-Controller/CarDetailServlet.class[m[m
[31m-[31m-Controller/StaffPartServlet.class[m[m
[31m-[31m-com/mycompany/drivexo_management_project/JakartaRestConfiguration.class[m[m
[31m-[31m-Controller/CartServlet.class[m[m
[31m-[31m-Model/Cart.class[m[m
[31m-[31m-Controller/CarListServlet.class[m[m
[31m-[31m-DB/TestDBConnect.class[m[m
[31m-[31m-com/mycompany/drivexo_management_project/resources/JakartaEE10Resource.class[m[m
[31m-[31m-Model/Order.class[m[m
[31m-[31m-Model/Part.class[m[m
[31m-[31m-DAO/UserDAO.class[m[m
[31m-[31m-Model/Service.class[m[m
[31m-[31m-DAO/ServiceDAO.class[m[m
[31m-[31m-DAO/ServiceScheduleDAO.class[m[m
[31m-[31m-DAO/OrderDetailDAO.class[m[m
[31m-[31m-Model/Comment.class[m[m
[31m-[31m-DAO/RoleDAO.class[m[m
[31m-[31m-Model/ServiceSchedule.class[m[m
[31m-[31m-Model/Payment.class[m[m
[31m-[31m-Controller/AdminPartServlet.class[m[m
[31m-[31m-Controller/BookingsServlet.class[m[m
[31m-[31m-Controller/PartServlet.class[m[m
[31m-[31m-DAO/PartDAO.class[m[m
[31m-[31m-Model/CarAppointment.class[m[m
[31m-[31m-Model/Car.class[m[m
[31m-[32m+[m[32mDAO\CartDAO.class[m[m
[31m-[32m+[m[32mModel\CarAppointment.class[m[m
[31m-[32m+[m[32mDAO\CarAppointmentDAO.class[m[m
[31m-[32m+[m[32mModel\Part.class[m[m
[31m-[32m+[m[32mModel\Category.class[m[m
[31m-[32m+[m[32mController\AdminDashboardServlet.class[m[m
[31m-[32m+[m[32mController\CarImageServlet.class[m[m
[31m-[32m+[m[32mDAO\CarDAO.class[m[m
[31m-[32m+[m[32mDAO\ServiceDAO.class[m[m
[31m-[32m+[m[32mController\BookingsServlet.class[m[m
[31m-[32m+[m[32mModel\Car.class[m[m
[31m-[32m+[m[32mModel\Cart.class[m[m
[31m-[32m+[m[32mDAO\PartDAO.class[m[m
[31m-[32m+[m[32mDAO\ServiceScheduleDAO.class[m[m
[31m-[32m+[m[32mModel\Comment.class[m[m
[31m-[32m+[m[32mDAO\RoleDAO.class[m[m
[31m-[32m+[m[32mController\CarListServlet.class[m[m
[31m-[32m+[m[32mcom\mycompany\drivexo_management_project\JakartaRestConfiguration.class[m[m
[31m-[32m+[m[32mController\AddToCartServlet.class[m[m
[31m-[32m+[m[32mDAO\OrderDetailDAO.class[m[m
[31m-[32m+[m[32mController\AdminCarServlet.class[m[m
[31m-[32m+[m[32mModel\Service.class[m[m
[31m-[32m+[m[32mController\CartServlet.class[m[m
[31m-[32m+[m[32mModel\Order.class[m[m
[31m-[32m+[m[32mController\StaffPartServlet.class[m[m
[31m-[32m+[m[32mModel\Payment.class[m[m
[31m-[32m+[m[32mDAO\UserDAO.class[m[m
[31m-[32m+[m[32mDAO\OrderDAO.class[m[m
[31m-[32m+[m[32mDB\TestDBConnect.class[m[m
[31m-[32m+[m[32mcom\mycompany\drivexo_management_project\resources\JakartaEE10Resource.class[m[m
[31m-[32m+[m[32mController\CarDetailServlet.class[m[m
[31m-[32m+[m[32mController\AdminPartServlet.class[m[m
[31m-[32m+[m[32mModel\ServiceSchedule.class[m[m
[31m-[32m+[m[32mDB\DBContext.class[m[m
[31m-[32m+[m[32mModel\User.class[m[m
[31m-[32m+[m[32mController\PartServlet.class[m[m
[31m-[32m+[m[32mModel\Role.cla